#!/usr/bin/env python3
# pylint: disable=missing-module-docstring
from __future__ import annotations

from collections.abc import Sequence
from .utils import open_and_test_notebooks


def test_jetbrains_bug_py_66491(notebook):
    """checks if all notebook have the execution_count key for each cell in JSON,
    which is required by GitHub renderer and may not be generated by some buggy PyCharm versions:
    https://youtrack.jetbrains.com/issue/PY-66491"""
    for cell in notebook.cells:
        if cell.cell_type == "code" and not hasattr(cell, "execution_count"):
            raise ValueError(
                "Notebook cell missing execution_count attribute. "
                "(May be due to PyCharm bug, see: https://youtrack.jetbrains.com/issue/PY-66491 )"
            )


def main(argv: Sequence[str] | None = None) -> int:
    """test all notebooks"""
    return open_and_test_notebooks(
        argv=argv,
        test_functions=[
            test_jetbrains_bug_py_66491,
        ],
    )


if __name__ == "__main__":
    raise SystemExit(main())
